"""add is_active to UserGroupLink

Revision ID: a864183241e8
Revises: 8c581d376c2b
Create Date: 2026-06-12 13:06:11.137179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a864183241e8'
down_revision: Union[str, Sequence[str], None] = '8c581d376c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergrouplink', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usergrouplink', 'is_active')
    # ### end Alembic commands ###
